// config-shared-web-vue/templates/base/src/components/SidebarMenu.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRoute, RouterLink } from 'vue-router'
import type { SidebarMenuItem, SidebarMenuSection } from '@/config/shell-navigation'

const props = defineProps<{
  mainItem?: SidebarMenuItem
  sections: SidebarMenuSection[]
  collapsed?: boolean
}>()

const emit = defineEmits<{ navigate: [] }>()
const route = useRoute()

function isActive(item: SidebarMenuItem) {
  if (item.match === 'exact') return route.path === item.to
  return route.path === item.to || route.path.startsWith(`${item.to}/`)
}

const itemClass = computed(
  () =>
    'group relative flex h-10 items-center gap-3 rounded-md px-3 text-sm text-muted-foreground transition-colors hover:bg-accent hover:text-accent-foreground',
)
</script>

<template>
  <nav class="px-2 py-4">
    <div v-if="mainItem" class="space-y-1">
      <RouterLink
        :to="mainItem.to"
        :class="[itemClass, isActive(mainItem) && 'bg-accent text-accent-foreground', collapsed && 'justify-center px-2']"
        @click="emit('navigate')"
      >
        <span class="inline-flex size-4 shrink-0 items-center justify-center text-xs">⌂</span>
        <span v-if="!collapsed" class="truncate">{{ mainItem.label }}</span>
      </RouterLink>
      <div class="my-4 h-px bg-border" />
    </div>

    <div class="space-y-4">
      <div v-for="section in sections" :key="section.id">
        <p
          v-if="section.label"
          :class="collapsed ? 'sr-only' : 'px-3 pb-2 text-[11px] font-semibold uppercase tracking-[0.08em] text-muted-foreground'"
        >
          {{ section.label }}
        </p>
        <div class="space-y-1">
          <RouterLink
            v-for="item in section.items"
            :key="item.id"
            :to="item.to"
            :aria-label="collapsed ? item.label : undefined"
            :class="[itemClass, isActive(item) && 'bg-accent text-accent-foreground', collapsed && 'justify-center px-2']"
            @click="emit('navigate')"
          >
            <span class="inline-flex size-4 shrink-0 items-center justify-center text-xs">•</span>
            <span v-if="!collapsed" class="truncate">{{ item.label }}</span>
            <span
              v-if="collapsed"
              class="pointer-events-none absolute left-[calc(100%+10px)] top-1/2 z-50 hidden -translate-y-1/2 whitespace-nowrap rounded-md border border-border bg-card px-2 py-1 text-xs text-foreground shadow-md group-hover:block"
            >
              {{ item.label }}
            </span>
          </RouterLink>
        </div>
      </div>
    </div>
  </nav>
</template>

// config-shared-web/templates/base/src/shared/components/ui/sidebar-menu.component.tsx
'use client';

import type { ComponentType } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { Circle } from 'lucide-react';

type SidebarIcon = ComponentType<{ className?: string }>;

export type SidebarMenuItem = {
  id: string;
  label: string;
  href: string;
  icon?: SidebarIcon;
  description?: string;
  match?: 'exact' | 'prefix';
};

export type SidebarMenuSection = {
  id: string;
  label?: string;
  items: SidebarMenuItem[];
  dividerBefore?: boolean;
};

export type SidebarMenuProps = {
  mainItem?: SidebarMenuItem;
  sections: SidebarMenuSection[];
  collapsed?: boolean;
};

const ITEM_BASE_CLASS =
  'group relative flex h-10 items-center gap-3 rounded-md px-3 text-sm text-muted-foreground transition-colors hover:bg-accent hover:text-accent-foreground';
const COLLAPSED_CLASS = 'justify-center px-2';
const ACTIVE_CLASS = 'bg-accent text-accent-foreground';

function joinClassNames(values: Array<string | false | null | undefined>) {
  return values.filter(Boolean).join(' ');
}

function isItemActive(pathname: string, item: SidebarMenuItem) {
  if (item.match === 'exact') {
    return pathname === item.href;
  }

  return pathname === item.href || pathname.startsWith(`${item.href}/`);
}

function SidebarItemLink({
  item,
  active,
  collapsed,
}: {
  item: SidebarMenuItem;
  active: boolean;
  collapsed: boolean;
}) {
  const Icon = item.icon ?? Circle;

  return (
    <Link
      href={item.href}
      aria-label={collapsed ? item.label : undefined}
      className={joinClassNames([ITEM_BASE_CLASS, collapsed && COLLAPSED_CLASS, active && ACTIVE_CLASS])}
    >
      <Icon className="size-4 shrink-0" />
      <span className={joinClassNames(['truncate', collapsed && 'sr-only'])}>{item.label}</span>
      {collapsed ? (
        <span className="pointer-events-none absolute left-[calc(100%+10px)] top-1/2 z-50 hidden -translate-y-1/2 whitespace-nowrap rounded-md border border-border bg-popover px-2 py-1 text-xs text-popover-foreground shadow-md group-hover:block group-focus-visible:block">
          {item.label}
        </span>
      ) : null}
    </Link>
  );
}

export function SidebarMenu({ mainItem, sections, collapsed = false }: SidebarMenuProps) {
  const pathname = usePathname();

  return (
    <nav className="px-2 py-4">
      {mainItem ? (
        <>
          <div className="space-y-1">
            <SidebarItemLink item={mainItem} active={isItemActive(pathname, mainItem)} collapsed={collapsed} />
          </div>
          <div className="my-4 h-px bg-border" />
        </>
      ) : null}

      <div className="space-y-4">
        {sections.map((section, sectionIndex) => (
          <div key={section.id}>
            {section.dividerBefore && sectionIndex > 0 ? <div className="mb-4 h-px bg-border" /> : null}
            {section.label ? (
              !collapsed ? (
                <p className="px-3 pb-2 text-[11px] font-semibold uppercase tracking-[0.08em] text-muted-foreground">
                  {section.label}
                </p>
              ) : (
                <p className="sr-only">{section.label}</p>
              )
            ) : null}

            <div className="space-y-1">
              {section.items.map((item) => (
                <SidebarItemLink key={item.id} item={item} active={isItemActive(pathname, item)} collapsed={collapsed} />
              ))}
            </div>
          </div>
        ))}
      </div>
    </nav>
  );
}
